[package]
name = "thiagohaga/template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Networking & Buffer Serialization
# Decided to use red-blox/zap that is set at rokit.toml

# Event Passing & Signals
LemonSignal = "data-oriented-house/lemonsignal@^2.0.0"

# Asynchronous Control Flow
Promise = "evaera/promise@^4.0.0"

# Resource & Lifetime Cleanup
Janitor = "howmanysmall/janitor@^1.18.3"

# Component Helper (Optional)
Component = "sleitnick/component@^2.4.8"

[dev-dependencies]
# Modern Unit & Integration Testing (Jest-Luau via jsdotlua)
# JestGlobals = "jsdotlua/jest-globals@3.10.0"
# Jest = "jsdotlua/jest@^3.10.0"

[server-dependencies]
# Reads sql, necessary to get the teams for carreer
ProfileService = "firebird702/profileservice@1.1.0"